/* BlueThread: simple browser-only store functions powered by localStorage */
const products=[
 {id:1,name:'Classic Linen Shirt',category:'Men',type:'Shirts',price:42,old:56,rating:4.7,discount:'25%',image:'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80'},
 {id:2,name:'Essential Cotton Tee',category:'Men',type:'T-Shirts',price:24,old:0,rating:4.8,discount:'',image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80'},
 {id:3,name:'Tailored Wide Leg Jeans',category:'Women',type:'Jeans',price:58,old:72,rating:4.6,discount:'20%',image:'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80'},
 {id:4,name:'Satin Midi Dress',category:'Women',type:'Dresses',price:68,old:0,rating:4.9,discount:'',image:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=600&q=80'},
 {id:5,name:'Everyday Denim Jacket',category:'Women',type:'Jackets',price:64,old:80,rating:4.5,discount:'20%',image:'https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=600&q=80'},
 {id:6,name:'Relaxed Fit Trousers',category:'Men',type:'Trousers',price:48,old:0,rating:4.4,discount:'',image:'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=600&q=80'},
 {id:7,name:'Mini Explorer Set',category:'Kids',type:'T-Shirts',price:29,old:39,rating:4.8,discount:'25%',image:'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=600&q=80'},
 {id:8,name:'Little Party Dress',category:'Kids',type:'Dresses',price:35,old:0,rating:4.7,discount:'',image:'https://images.unsplash.com/photo-1519278409-1f56f5a0e832?auto=format&fit=crop&w=600&q=80'},
 {id:9,name:'Leather Crossbody Bag',category:'Accessories',type:'Bags',price:52,old:65,rating:4.6,discount:'20%',image:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80'},
 {id:10,name:'Minimal White Sneakers',category:'Men',type:'Shoes',price:70,old:0,rating:4.8,discount:'',image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80'},
 {id:11,name:'Soft Knit Top',category:'Women',type:'Tops',price:38,old:0,rating:4.5,discount:'',image:'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=600&q=80'},
 {id:12,name:'Color Pop Sneakers',category:'Kids',type:'Shoes',price:32,old:42,rating:4.6,discount:'24%',image:'https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=600&q=80'}
];
const get=(key)=>JSON.parse(localStorage.getItem(key)||'[]'); const set=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
function nav(){return `<nav class="navbar navbar-expand-lg navbar-light bg-white sticky-top shadow-sm"><div class="container"><a class="navbar-brand fw-bold" href="index.html"><i class="bi bi-bag-heart-fill"></i> BlueThread</a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="nav"><ul class="navbar-nav mx-auto"><li class="nav-item"><a class="nav-link" href="index.html">Home</a></li><li class="nav-item"><a class="nav-link" href="shop.html">Shop</a></li><li class="nav-item"><a class="nav-link" href="categories.html">Categories</a></li><li class="nav-item"><a class="nav-link" href="men.html">Men</a></li><li class="nav-item"><a class="nav-link" href="women.html">Women</a></li><li class="nav-item"><a class="nav-link" href="kids.html">Kids</a></li><li class="nav-item"><a class="nav-link" href="about.html">About</a></li><li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li></ul><div class="nav-actions"><button class="icon-btn" data-search-toggle><i class="bi bi-search"></i></button><a class="icon-btn" href="wishlist.html"><i class="bi bi-heart"></i><span class="badge-count wishlist-count">0</span></a><a class="icon-btn" href="cart.html"><i class="bi bi-bag"></i><span class="badge-count cart-count">0</span></a><a class="btn btn-primary btn-sm ms-2" href="login.html">Login</a></div></div></div></nav><div class="search-bar py-3 bg-light d-none"><div class="container"><input class="form-control" data-product-search placeholder="Search products..."></div></div>`}
function footer(){return `<footer class="footer pt-5"><div class="container"><div class="row g-4 pb-4"><div class="col-lg-4"><a class="navbar-brand text-white" href="index.html"><i class="bi bi-bag-heart-fill"></i> BlueThread</a><p class="mt-3">Modern essentials and standout pieces for a wardrobe that feels like you.</p><div class="socials"><a href="#"><i class="bi bi-instagram"></i></a><a href="#"><i class="bi bi-facebook"></i></a><a href="#"><i class="bi bi-pinterest"></i></a></div></div><div class="col-6 col-lg-2"><h6>Quick Links</h6><a href="shop.html">Shop</a><a href="categories.html">Categories</a><a href="about.html">About us</a></div><div class="col-6 col-lg-3"><h6>Customer Care</h6><a href="contact.html">Contact us</a><a href="wishlist.html">Wishlist</a><a href="cart.html">Shopping cart</a></div><div class="col-lg-3"><h6>Contact</h6><p><i class="bi bi-geo-alt"></i> 125 Fashion Street, Yangon</p><p><i class="bi bi-envelope"></i> hello@bluethread.com</p><p><i class="bi bi-telephone"></i> +95 9 123 456 789</p></div></div><div class="footer-bottom d-flex justify-content-between flex-wrap gap-2"><span>© 2026 BlueThread. All rights reserved.</span><span><i class="bi bi-credit-card fs-4"></i> <i class="bi bi-paypal fs-4"></i></span></div></div></footer>`}
function productCard(p){let wished=get('btWishlist').includes(p.id);return `<div class="col-12 col-sm-6 col-md-4 col-xl-3"><article class="product-card position-relative"><a href="product-details.html"><img class="product-image" src="${p.image}" alt="${p.name}"></a>${p.discount?`<span class="discount-badge">-${p.discount}</span>`:''}<button class="wish-btn ${wished?'active':''}" data-wishlist="${p.id}" aria-label="Add to wishlist"><i class="bi bi-heart${wished?'-fill':''}"></i></button><div class="card-body"><span class="product-category">${p.category} · ${p.type}</span><h5 class="product-title">${p.name}</h5><div class="rating"><i class="bi bi-star-fill"></i> ${p.rating}</div><div class="my-2"><span class="price">$${p.price.toFixed(2)}</span>${p.old?`<span class="old-price">$${p.old.toFixed(2)}</span>`:''}</div><div class="product-actions"><button class="btn btn-primary flex-grow-1" data-add-cart="${p.id}"><i class="bi bi-bag-plus"></i> Add to Cart</button><a class="btn btn-outline-primary" href="product-details.html">Details</a></div></div></article></div>`}
function renderProducts(list=products){document.querySelectorAll('.product-list').forEach(el=>{let data=list;let category=el.dataset.collection;if(category)data=data.filter(p=>p.category===category);if(el.dataset.limit)data=data.slice(0,+el.dataset.limit);el.innerHTML=data.map(productCard).join('')});let count=document.querySelector('[data-result-count]');if(count)count.textContent=list.length}
function updateCounts(){document.querySelectorAll('.cart-count').forEach(e=>e.textContent=get('btCart').reduce((sum,i)=>sum+i.quantity,0));document.querySelectorAll('.wishlist-count').forEach(e=>e.textContent=get('btWishlist').length)}
function message(text){let box=document.querySelector('.toast-container');if(!box)return;box.innerHTML=`<div class="toast align-items-center text-bg-primary border-0" role="alert"><div class="d-flex"><div class="toast-body">${text}</div><button class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button></div></div>`;new bootstrap.Toast(box.querySelector('.toast')).show()}
function addCart(id,qty=1){let cart=get('btCart'),item=cart.find(x=>x.id===+id);if(item)item.quantity+=qty;else cart.push({id:+id,quantity:qty,size:'M',color:'Blue'});set('btCart',cart);updateCounts();message('Added to your cart')}
function toggleWish(id){let w=get('btWishlist'),i=w.indexOf(+id);i>-1?w.splice(i,1):w.push(+id);set('btWishlist',w);renderProducts();renderWishlist();updateCounts();message(i>-1?'Removed from wishlist':'Saved to your wishlist')}
function totals(){let cart=get('btCart'),subtotal=cart.reduce((s,x)=>s+(products.find(p=>p.id===x.id)?.price||0)*x.quantity,0),discount=0,shipping=subtotal===0?0:subtotal>=75?0:8,tax=(subtotal-discount)*.05,total=subtotal-discount+shipping+tax;return{subtotal,discount,shipping,tax,total}}
function renderCart(){let target=document.querySelector('#cart-items');if(!target)return;let cart=get('btCart');target.innerHTML=cart.map(x=>{let p=products.find(p=>p.id===x.id);return `<div class="cart-item d-flex gap-3 align-items-center"><img src="${p.image}" alt="${p.name}"><div class="flex-grow-1"><h6 class="mb-1">${p.name}</h6><small class="text-secondary">Size: ${x.size} · Color: ${x.color}</small><div class="price mt-1">$${p.price.toFixed(2)}</div></div><div class="qty-control"><button data-cart-qty="${x.id}" data-change="-1">−</button><input value="${x.quantity}" readonly><button data-cart-qty="${x.id}" data-change="1">+</button></div><b>$${(p.price*x.quantity).toFixed(2)}</b><button class="btn btn-link text-danger" data-remove-cart="${x.id}"><i class="bi bi-trash"></i></button></div>`}).join('');document.querySelector('#empty-cart')?.classList.toggle('d-none',cart.length>0);renderSummary();}
function renderSummary(){let t=totals();Object.entries(t).forEach(([key,val])=>document.querySelectorAll(`[data-summary="${key}"]`).forEach(e=>e.textContent=`${key==='discount'?'-':''}$${val.toFixed(2)}`));let checkout=document.querySelector('#checkout-products');if(checkout)checkout.innerHTML=get('btCart').map(x=>{let p=products.find(p=>p.id===x.id);return `<div class="d-flex justify-content-between py-2"><span>${p.name} × ${x.quantity}</span><b>$${(p.price*x.quantity).toFixed(2)}</b></div>`}).join('')||'<p class="text-secondary">Your cart is empty.</p>'}
function renderWishlist(){let el=document.querySelector('#wishlist-products');if(!el)return;let saved=products.filter(p=>get('btWishlist').includes(p.id));el.innerHTML=saved.map(productCard).join('');document.querySelector('#empty-wishlist')?.classList.toggle('d-none',saved.length>0)}
function categories(){let list=[['Men\'s Clothing','Men','https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=600&q=80'],['Women\'s Clothing','Women','https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=600&q=80'],['Kids\' Clothing','Kids','https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=600&q=80'],['Shoes','Shop','https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80'],['Bags','Shop','https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80'],['Accessories','Shop','https://images.unsplash.com/photo-1523779917675-b6ed3a42a561?auto=format&fit=crop&w=600&q=80'],['Jackets','Men','https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=600&q=80'],['T-Shirts','Shop','https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80'],['Jeans','Women','https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80']];let grid=document.querySelector('#category-grid');if(grid)grid.innerHTML=list.map((c,i)=>`<div class="col-sm-6 col-lg-4"><article class="category-card"><img src="${c[2]}" alt="${c[0]}"><div><h4>${c[0]}</h4><p class="mb-2 small">${18+i*9} products</p><a href="${c[1].toLowerCase()}.html" class="btn btn-light btn-sm">Shop Now</a></div></article></div>`).join('')}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-nav]').forEach(e=>e.innerHTML=nav());document.querySelectorAll('[data-footer]').forEach(e=>e.innerHTML=footer());renderProducts();renderCart();renderWishlist();renderSummary();categories();updateCounts();
document.addEventListener('click',e=>{let a=e.target.closest('[data-add-cart]');if(a){addCart(a.dataset.addCart,a.dataset.addCart==='1'?(+document.querySelector('[data-detail-qty]')?.value||1):1)}let w=e.target.closest('[data-wishlist]');if(w)toggleWish(w.dataset.wishlist);let q=e.target.closest('[data-cart-qty]');if(q){let c=get('btCart'),x=c.find(v=>v.id===+q.dataset.cartQty);x.quantity+=+q.dataset.change;if(x.quantity<1)c.splice(c.indexOf(x),1);set('btCart',c);renderCart();updateCounts()}let rem=e.target.closest('[data-remove-cart]');if(rem){set('btCart',get('btCart').filter(x=>x.id!==+rem.dataset.removeCart));renderCart();updateCounts();message('Item removed')}let dq=e.target.closest('[data-qty-change]');if(dq){let input=document.querySelector('[data-detail-qty]');input.value=Math.max(1,+input.value + +dq.dataset.qtyChange)}if(e.target.closest('[data-search-toggle]'))document.querySelector('.search-bar')?.classList.toggle('d-none');if(e.target.closest('[data-buy-now]')){addCart(1,+document.querySelector('[data-detail-qty]').value);location.href='checkout.html'}});
document.querySelectorAll('[data-sort]').forEach(s=>s.addEventListener('change',()=>{let sorted=[...products];if(s.value==='low')sorted.sort((a,b)=>a.price-b.price);if(s.value==='high')sorted.sort((a,b)=>b.price-a.price);if(s.value==='best')sorted.sort((a,b)=>b.rating-a.rating);renderProducts(sorted)}));document.querySelector('[data-filter="category"]')?.addEventListener('change',e=>renderProducts(e.target.value?products.filter(p=>p.category===e.target.value):products));document.querySelector('[data-price-filter]')?.addEventListener('input',e=>renderProducts(products.filter(p=>p.price<=+e.target.value)));document.querySelector('[data-clear-filters]')?.addEventListener('click',()=>renderProducts());document.querySelectorAll('[data-product-search]').forEach(i=>i.addEventListener('input',()=>renderProducts(products.filter(p=>p.name.toLowerCase().includes(i.value.toLowerCase())||p.type.toLowerCase().includes(i.value.toLowerCase())))));
document.querySelectorAll('.thumb').forEach(t=>t.addEventListener('click',()=>document.querySelector('#main-product-image').src=t.src));document.querySelectorAll('.needs-validation').forEach(form=>form.addEventListener('submit',e=>{if(form.matches('[data-register-form]')&&document.querySelector('#password').value!==document.querySelector('#confirm-password').value){document.querySelector('#confirm-password').setCustomValidity('Mismatch')}else document.querySelector('#confirm-password')?.setCustomValidity('');if(!form.checkValidity()){e.preventDefault();e.stopPropagation()}else{e.preventDefault();message(form.matches('[data-checkout-form]')?'Order placed successfully!':form.matches('[data-contact-form]')?'Message sent — thank you!':'Success! Your account is ready.')}form.classList.add('was-validated')}));document.querySelector('.newsletter-form')?.addEventListener('submit',e=>{e.preventDefault();message('Thanks for subscribing!')});
let cd=document.querySelector('[data-countdown]');if(cd){let end=Date.now()+86400000*5;setInterval(()=>{let x=Math.max(0,end-Date.now()),v=[Math.floor(x/864e5),Math.floor(x/36e5)%24,Math.floor(x/6e4)%60,Math.floor(x/1e3)%60];cd.querySelectorAll('b').forEach((b,i)=>b.textContent=String(v[i]).padStart(2,'0'))},1000)}});
